### ISSUE TITLE
Blobulator test command fails: path to ncprCMap.csv not found

### ISSUE THREAD

**Issue by mebh** [BranniganLab/blobulator#369]
The initial test command for the stand-alone tool in the README is:
`python3 compute_blobs.py --sequence AFRPGAGQPPRRKECTPEVEEGV --oname ./my_blobulation.csv`

I modified this to reflect the current location of the compute_blobs.py script, and tried running:
`python3 library/compute_blobs.py --sequence AFRPGAGQPPRRKECTPEVEEGV --oname ./my_blobulation.csv`

This fails with the error:

```
Traceback (most recent call last):
  File "/Users/mhansen/Dropbox/Science/Projects/Blobulator_Tool/blobulator-main/library/compute_blobs.py", line 167, in <module>
    ncprDict = pd.read_csv("../data/ncprCMap.csv", index_col=0)
  File "/Users/mhansen/opt/miniconda3/envs/blobulator_env/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/mhansen/opt/miniconda3/envs/blobulator_env/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/mhansen/opt/miniconda3/envs/blobulator_env/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/mhansen/opt/miniconda3/envs/blobulator_env/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/Users/mhansen/opt/miniconda3/envs/blobulator_env/lib/python3.9/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '../data/ncprCMap.csv'
```

**Comment by EzryStIago** [comment]
Temporary fix: execute inside Library

Fix in progress: packaging. Progress can be found in [packaging](/BranniganLab/blobulator/tree/packaging)
